### PR TITLE
Remove the default zip extension and use instead the proposed online for NL

### PR DESCRIPTION
**Pull request by marcelrv**
Fixing https://github.com/chartcatalogs/catalogs/issues/33 for Netherlands

### CODE REVIEW

**Comment by nohal** [comment]
Thanks. Isn't `urllib.request` only available in Python 3? The machine running  the job is CentOS 7, so I will have to check if it actually works there.

**Comment by nohal** [comment]
I have implemented it in a Python 2 compatible way.
Do we still need to increase the frequency of automatic updates to more than once a week or does this address the whole issue?

**Comment by marcelrv** [comment]
Thanks!
It does not address the refresh issue.
It would be great if the frequency van be increased

**Comment by nohal** [comment]
OK, I have set the cron job to run daily.

**Pull request closed without merging**
