### PR TITLE
Create EURIS IENC catalog file

### PR DESCRIPTION
**Pull request by OgreTransporter**
Python script to create an EURIS IENC catalog file.

### CODE REVIEW

**Comment by nohal** [comment]
Many thanks, very nice!

To make the result more user friendly we probably need to extend the `title` field with the content of `Description`. And maybe even `Areas. IENCAreaDTO. AreaName` to make even this one make sense:

```xml
<IENCOverviewMap>
<Areas>
  <IENCAreaDTO>
    <AreaCode>Rhein-Herne-Kanal</AreaCode>
    <AreaName>Rhein-Herne-Kanal</AreaName>
    <IencAreaID>00000000-0000-0000-0000-000000000000</IencAreaID>
    <IencMapID>00000000-0000-0000-0000-000000000000</IencMapID>
  </IENCAreaDTO>
</Areas>
<DencUsage>64</DencUsage>
<Description>km 10 - km 20</Description>
<Downloads/>
<FilesModifiedDate>2021-05-03T14:56:17.143</FilesModifiedDate>
<IsUpdated i:nil="true"/>
<MapID>071c5822-9bb6-44e1-9c93-0097e586e5f5</MapID>
<Name>1W7RHK01</Name>
<Status>1</Status>
<StatusClass/>
<StatusTooltip/>
<SubscribersCount>0</SubscribersCount>
<Usage>3</Usage>
</IENCOverviewMap>
```

**Comment by OgreTransporter** [comment]
Yes, I thought about that too, but this data is not available for all data records. I also didn't have the time to expand and test it quickly.

**Comment by nohal** [comment]
All done now. I have also added sorting of the cells before the catalog is generated so that the ones from same area are presented together. So even if the names are missing (like in case of some Hungarian cells at the beginning of the list), it should be clear from the neighboring cells that it is the same area.
Still the 1300 cells would probably deserve splitting into multiple catalogs, but the question is based on what - There are too many IENC areas and I don't see anything else useful...

**Comment by OgreTransporter** [comment]
Well, you can also just call up the map ID list and then call up the details for each map individually. The metadata also contains the bounding box in geocoordinates. Then, of course, you can use geopolygons to see which country they are in and create country catalogs again.

**Comment by nohal** [comment]
It would probably be simpler to implement similar logic based on the cell naming - they start with the identifier of the HO that creates them, which can be mapped to the country, but still it would mean stuff that needs maintenance, which I want to avoid...

**Comment by OgreTransporter** [comment]
I'll try to find out.

**Comment by nohal** [comment]
The producer codes are managed by IHO and can be downloaded from https://registry.iho.int/producercode/list2.do, that is the good news.
But as usually there is a but :) The mapping of the IENC agencies to countries is not always present...

**Comment by OgreTransporter** [comment]
Unfortunately, the lists do nothing to assign the map parts to specific countries based on their names. I tried it once with Germany. The fragments start with 1W7 or 9H7. In addition, if you look at the Rhine on the border between France and Germany, for example, some of the fragments are created by Germany and some by France. A geolocalized catalog would make more sense.

**Comment by nohal** [comment]
The corner cases will always be there in the border areas - the cells do not correspond with the actual borders (so sourcing the polygons to overlay will be complicated) and there often is an overlap (For example Elbe crossing the CZ/DE border is covered by both 1W and 9D cells)

**Pull request merged**
